openapi: 3.0.3
info:
  version: '1.0'
  title: 'OpenAPI Course'
  description: 'Specification for OpenAPI Course'
  termsOfService: https://example.com/terms
  contact: 
    name: Rouche
    url: https://github.com/Rouche
    email: rouche@server.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers: 
  - url: https://dev.example.com
    description: DEV server
  - url: https://qa.example.com
    description: QA server
  - url: https://prod.example.com
    description: PROD server
paths:
  /v1/customers:
    get:
      responses:
        '200': 
          description: List of customers
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 100
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    firstName: 
                      type: string
                      minLength: 2
                      maxLength: 100
                    lastNamne:
                      type: stirng
                      minLength: 2
                      maxLength: 100
                      example: Fuck!
                    address:
                      type: object
                      properties:
                        line1:
                          type: string
                        city:
                          type: string
                          example: Zomg!
                        zipCode:
                          type: string
  /v1/beers:
    get:
      responses:
        '200': 
          description: List of customers
          content:
            application/json:
              schema:
                type: array
                minItems: 1
                maxItems: 100
                items:
                  type: string
                  description: Customer Name
                  minLength: 2
                  maxLength: 100
        '404':
          description: Not found